#!/bin/bash

# Simple script to rename the current workspace for Xfce4. It takes no
# arguments, instead it opens a dialog box.
#
# Requirements:
#
# 1) wmctrl (tested with 1.07)
#
# 2) zenity (tested with 3.6.0)

# Raise error on read if variable is not previously written 
set -u

# # Debug trace
# set -x

# Current workspace output by wmctrl
curnt_ws_idx=$(wmctrl -d | grep '*' | cut -d " " -f1) # current workspace id

# Get the names of all the workspaces
ws_names=()
while read name; do
    ws_names+=("$name")
done < <(xfconf-query -c xfwm4 -p /general/workspace_names | tail -n +3)

# Get new workspace name via zenity
new_name=$(zenity --entry --title="Rename workspace" \
    --text="Rename workspace $((curnt_ws_idx + 1))" --entry-text="${ws_names[$curnt_ws_idx]}")

# Overwrite current workspace name
xfconf_cmd="xfconf-query -c xfwm4 -p /general/workspace_names"
for i in ${!ws_names[@]}; do
    if [[ $i == $curnt_ws_idx && $new_name ]]; then
        xfconf_cmd+=" -s \"$new_name\""
    else
        xfconf_cmd+=" -s \"${ws_names[$i]}\""
    fi
done
eval $xfconf_cmd
